config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

  devise_for :users
  root :to =>"homes#top"
  get "home/about"=>"homes#about"
  get "search" => "searches#search"

  resources :books, only: [:index,:show,:edit,:create,:destroy,:update] do
    resources :book_comments, only: [:create, :destroy]
    resource :favorites, only: [:create, :destroy]
  end
  resources :users, only: [:index,:show,:edit,:update] do
    resource :relationships, only: [:create, :destroy]
    get :followings, on: :member
    # あるユーザーがフォローしている人全員を表示するためのルーティング
    get :followers, on: :member
    # あるユーザーフォローしてくれている人（フォロワー）全員を表示するための
  end
  resources :groups, only: [:index, :new, :show, :edit, :create, :update, :destroy] do
    get "join" => "groups#join"
    get "new/mail" => "groups#new_mail"
    get "send/mail" => "groups#send_mail"
  end

  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/group.rb
class Group < ApplicationRecord
  has_many :group_users, dependent: :destroy
  has_many :users, through: :group_users
  # usersはthrough記述で中間テーブルを通じてgroupsにアクセスできるようにする

  validates :name, presence: true
  validates :introduction, presence: true

  has_one_attached :image

  def get_image
    (image.attached?) ? image : 'no_image.jpg'
  end
end

app/controllers/groups_controller.rb
class GroupsController < ApplicationController
  before_action :authenticate_user!
  before_action :ensure_correct_user, only: [:edit, :update]

  def new
    @group = Group.new
  end

  def index
    @groups = Group.all
    @book = Book.new
  end

  def join
    @group = Group.find(params[:group_id])
    @group.users << current_user
    # @group.usersにcurrent_userを追加する
    redirect_to groups_path
  end

  def create
    @group = Group.new(group_params)
    @group.owner_id = current_user.id
    @group.users << current_user
    # joinで記述した内容と同じ。これを記述しないとグループ作成者がメンバーとしてカウントされない
    if @group.save
      redirect_to groups_path
    else
      render :new
    end
  end

  def show
    @group = Group.find(params[:id])
    @book = Book.new
  end


  def edit
    @group = Group.find(params[:id])
    unless @group.owner_id == current_user.id
      redirect_to groups_path
    end
  end

  def update
    @group = Group.find(params[:id])
    if @group.update(group_params)
      redirect_to groups_path
    else
      render :edit
    end
  end

  def destroy
    @group = Group.find(params[:id])
    @group.users.destroy(current_user)
    # current_userは@group.usersから削除される
    redirect_to groups_path
  end
  
  def new_mail
    @group = Group.find(params[:group_id])
  end
  
  def send_mail
    @group = Group.find(params[:group_id])
    group_users = @group.users
    @mail_title = params[:mail_title]
    @mail_content = params[:mail_content]
    ContactMailer.send_mail(@mail_title,@mail_content,group_users).deliver
    # contact_mailer.rbのsend_mailアクションに前述の内容を渡している
  end


  private

  def group_params
    params.require(:group).permit(:name, :introduction, :image)
  end

  def ensure_correct_user
    @group = Group.find(params[:id])
    unless @group.owner_id == current_user.id
      redirect_to groups_path
    end
  end

end

app/helpers/groups_helper.rb
module GroupsHelper
end

app/views/groups/edit.html.erb
<div class='container'>
  <div class='row'>
    <div class="col-sm-12 col-md-8 col-lg-5 px-5 px-sm-0 mx-auto">
      <h3>Edit Group</h3>
        <%= form_with model: @group, method: :patch, local:true do |f| %>
          <div class="form-group">
            <%= f.label :グループ名 %>
            <%= f.text_field :name, class:"form-control" %>
          </div>
          <div class="form-group">
            <%= f.label :紹介文 %>
            <%= f.text_area :introduction, class:"form-control" %>
          </div>
          <div class="form-group">
            <%= f.label :グループ画像 %>
            <%= f.file_field :image, class:"form-control-file" %>
          </div>
          <div class="form-group">
            <%= f.submit "Create Group", class:"btn btn-info" %>
          </div>
        <% end %>
    </div>
  </div>
</div>

app/views/groups/index.html.erb
<div class='container'>
  <div class='row'>
    <div class='col-md-3'>
      <h2>User info</h2>
      <%= render 'users/info', user: current_user %>
      <h2 class="mt-3">New book</h2>
      <%= render 'books/form', book: @book %>
    </div>
    <div class='col-md-8 offset-md-1'>
      <h2>Groups</h2>
      <table class="table">
        <thead>
          <tr>
            <th></th>
            <th>グループ名</th>
            <th>紹介文</th>
            <th>メンバー数</th>
          </tr>
        </thead>
        <% @groups.each do |group| %>
        <tbody>
          <tr>
            <td><%= image_tag group.get_image, size: "40x40" %></td>
            <td><%= link_to group.name, group_path(group) %></td>
            <td><%= group.introduction %></td>
            <td><%= group.users.count %></td>
            <% if group.owner_id == current_user.id %>
              <td><%= link_to "Edit", edit_group_path(group), class:"btn btn-success" %></td>
            <% end %>
          </tr>
        </tbody>
        <% end %>
      </table>
    </div>
  </div>
</div>

app/views/groups/new.html.erb
<div class='container'>
  <div class='row'>
    <div class="col-sm-12 col-md-8 col-lg-5 px-5 px-sm-0 mx-auto">
      <h3>Create Group</h3>
      <%= form_with model: @group, local:true do |f| %>
        <div class="form-group">
          <%= f.label :グループ名 %>
          <%= f.text_field :name, class:"form-control" %>
        </div>
        <div class="form-group">
          <%= f.label :紹介文 %>
          <%= f.text_area :introduction, class:"form-control" %>
        </div>
        <div class="form-group">
          <%= f.label :グループ画像 %>
          <%= f.file_field :image, class:"form-control-file" %>
        </div>
        <div class="form-group">
          <%= f.submit "Create Group", class:"btn btn-info" %>
        </div>
      <% end %>
    </div>
  </div>
</div>

app/views/groups/new_mail.html.erb
<div class='container'>
  <div class='row'>
    <div class="col-sm-12 col-md-8 col-lg-5 px-5 px-sm-0 mx-auto">
      <h2>Event Mail</h2>
      <%= form_with url: group_send_mail_path(@group), method: :get, local: true do |f| %>
      <div class="form-group">
        <%= f.label :title %>
        <%= f.text_field :mail_title,class:'form-control' %>
      </div>
      <div class="form-group">
        <%= f.label :content %>
        <%= f.text_area :mail_content,class:'form-control' %>
      </div>
      <div class="text-right">
        <%= f.submit '送信', class:"btn btn-sm btn-success" %>
      </div>
      <% end %>
    </div>
  </div>
</div>

app/views/groups/send_mail.html.erb
<div class="container">
  <h3 class="margin_top text-center">送信が完了しました</h3>
  <div class="main_width">
    <div class="margin_top">内容は以下の通りです。</div>
    <div class="small_margin_top">
      [タイトル]<P class="font-weit-bold"><%= @mail_title %></P>
    </div>
    <div>
      [本文]<p class="font-weight-bold"><%= safe_join(@mail_content.split("\n"),tag(:br)) %></p>
    </div>
  </div>
</div>

app/views/groups/show.html.erb
<div class='container'>
  <div class='row'>
    <div class='col-md-3'>
      <h2>User info</h2>
      <%= render 'users/info', user: current_user %>
      <h2 class="mt-3">New book</h2>
      <%= render 'books/form', book: @book %>
    </div>
    <div class='col-md-8 offset-md-1'>
      <h2>Group Detail</h2>
      <table class="table">
        <thead>
          <tr>
            <th></th>
            <th>グループ名</th>
            <th>紹介文</th>
            <th>メンバー</th>
          </tr>
        </thead>
        <tbody>
          <tr>
            <td><%= image_tag @group.get_image, size: "40x40" %></td>
            <td><%= @group.name %></td>
            <td><%= @group.introduction %></td>
            <td>
              <% @group.users.each do |member| %>
                <%= member.name %>
              <% end %>
            </td>
            <td>
            <% if current_user.id == @group.owner_id %>
              <%= link_to "Edit", edit_group_path(@group), class:"btn btn-success" %>
            <% elsif @group.users.include?(current_user) %>
              <%= link_to "Leave this group", group_path(@group), method: :delete, class:"btn btn-sm btn-danger" %>
            <% else %>
              <%= link_to "Join this group", group_join_path(@group), class:"btn btn-sm btn-success" %>
            <% end %>
            </td>
            <td>
              <% if current_user.id == @group.owner_id %>
                <%= link_to "Notice an Event",group_new_mail_path(@group), class:"btn btn-info" %>
              <% end %>
            </td>
          </tr>
        </tbody>
      </table>
    </div>
  </div>
</div>