config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

  devise_for :users
  root :to =>"homes#top"
  get "home/about"=>"homes#about"
  get "search" => "searches#search"

  resources :books, only: [:index,:show,:edit,:create,:destroy,:update] do
    resources :book_comments, only: [:create, :destroy]
    resource :favorites, only: [:create, :destroy]
  end
  resources :users, only: [:index,:show,:edit,:update] do
    resource :relationships, only: [:create, :destroy]
    get :followings, on: :member
    # あるユーザーがフォローしている人全員を表示するためのルーティング
    get :followers, on: :member
    # あるユーザーフォローしてくれている人（フォロワー）全員を表示するための
  end
  resources :groups, only: [:index, :new, :show, :edit, :create, :update, :destroy] do
    get "join" => "groups#join"
    get "new/mail" => "groups#new_mail"
    get "send/mail" => "groups#send_mail"
  end

  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  has_many :books, dependent: :destroy
  has_many :favorites, dependent: :destroy
  has_many :book_comments, dependent: :destroy
  has_many :group_users, dependent: :destroy

  # フォローする側
  has_many :relationships, foreign_key: :following_id
  # relationshipsテーブルのfollowing_idを参照しにいく
  has_many :followings, through: :relationships, source: :follower
  # あるユーザーがフォローしている人(follower フォローされる人)全員を取ってくる

  # フォローされる
  has_many :reverse_of_relationships, class_name: "Relationship", foreign_key: :follower_id
  # relationshipsテーブルのfollower_idを参照しにいく(reverse_of~は存在しないテーブルなので、後にclass_nameで指定してあげる)
  has_many :followers, through: :reverse_of_relationships, source: :following
  # あるユーザーをフォローしてくれている人(following フォローする人)全てを取ってくる

  has_one_attached :profile_image

  validates :name, length: { minimum: 2, maximum: 20 }, uniqueness: true
  validates :introduction, length: {maximum: 50}

  def self.looks(searches,words)
    # searchアクションで使用するsearches,wordsを引数を受け取るlooksメソッド
    if searches == "perfect_match"
      @user = User.where("name LIKE ?", "#{words}")
    elsif searches == "forword_match"
      @user = User.where("name LIKE ?", "#{words}%")
    elsif searches == "backword_match"
      @user = User.where("name LIKE ?", "%#{words}")
    elsif searches == "partial_match"
      @user = User.where("name LIKE ?", "%#{words}%")
    else
      @user = User.all
    end
      # ＠userに該当するもの全てを受け取るようにwhereメソッドを使う
      # User.where("name LIKE?","#{word}%")これはユーザーモデルに検索ワードがヒットしているか確認できる
      # "#{words}"部分を書き換えることで前方一致や完全一致などの検索ができる
  end

  def is_followed_by?(user)
    reverse_of_relationships.find_by(following_id: user.id).present?
    # あるユーザーが引数(user)に渡されたユーザーにフォローされているのか？されていればtrueを返す
  end

  def get_profile_image
    (profile_image.attached?) ? profile_image : 'no_image.jpg'
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :ensure_correct_user, only: [:update, :edit]

  def show
    @user = User.find(params[:id])
    @books = @user.books
    @book = Book.new
  end

  def index
    @users = User.all
    @book = Book.new
    # @users_not = User.where.not(id: current_user.id)
    # ログインしているユーザー全てを取ってくる
  end

  def followings
    user = User.find(params[:id])
    @users = user.followings
    # ユーザーがフォローしている人全員を取ってくることができる
  end

  def followers
    user = User.find(params[:id])
    @users = user.followers
    # ユーザーをフォローしている人全員を取ってくることができる
  end

  def edit
    @user = User.find(params[:id])
  end

  def update
    if @user.update(user_params)
      redirect_to user_path(@user), notice: "You have updated user successfully."
    else
      render "edit"
    end
  end

  private

  def user_params
    params.require(:user).permit(:name, :introduction, :profile_image)
  end

  def ensure_correct_user
    @user = User.find(params[:id])
    unless @user == current_user
      redirect_to user_path(current_user)
    end
  end
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/users/_index.html.erb
<table class='table'>
  <thead>
    <tr>
      <th>image</th>
      <th>name</th>
      <th colspan="3"></th>
    </tr>
  </thead>
  <tbody>
    <% users.each do |user| %>
      <tr>
        <td><%= image_tag user.get_profile_image, size: '50x50' %></td>
        <td><%= user.name %></td>
        <td>フォロー数:<%= user.followings.count %></td>
        <td>フォロワー数:<%= user.followers.count %></td>
        <% if user != current_user %>
          <td>
          <% if user.is_followed_by?(current_user) %>
            <%= link_to user_relationships_path(user), method: :delete do %>
              <button class="btn btn-danger">フォロー解除</button>
            <% end %>
          <% elsif %>
            <%= link_to user_relationships_path(user), method: :post do %>
              <button class="btn btn-primary">フォロー</button>
            <% end %>
          <% end %>
          </td>
        <% end %>
        <td><%= link_to 'Show', user_path(user.id) %></td>
      </tr>
    <% end %>
  </tbody>
</table>

app/views/users/_info.html.erb
<table class='table'>
  <tr><%= image_tag user.get_profile_image, size:'100x100' %></tr>
  <tr>
	  <th>name</th>
	  <th><%= user.name %></th>
  </tr>
  <tr>
	  <th>introduction</th>
	  <th><%= user.introduction %></th>
  </tr>
  <tr>
	  <th>follows</th>
	  <th>
	    <%= link_to followings_user_path(user) do %>
	      <%= user.followings.count %>
	     <% end %>
    </th>
  </tr>
  <tr>
	  <th>followers</th>
	  <th>
	    <%= link_to followers_user_path(user) do %>
	      <%= user.followers.count %>
	     <% end %>
	  </th>
  </tr>
</table>

<% if user != current_user %>
  <% if user.is_followed_by?(current_user) %>
    <%= link_to user_relationships_path(user), method: :delete do %>
      <button class="btn btn-danger btn-block mb-3">フォロー解除</button>
    <% end %>
  <% elsif %>
    <%= link_to user_relationships_path(user), method: :post do %>
      <button class="btn btn-primary btn-block mb-3">フォロー</button>
    <% end %>
  <% end %>
<% end %>


<div class='row'>
  <%= link_to edit_user_path(user), class: "btn btn-outline-secondary btn-block edit_user_#{user.id}" do %>
    <i class="fas fa-user-cog"></i>
  <% end %>
</div>

app/views/users/edit.html.erb
<div class='container'>
  <div class='row'>
    <div class="col-sm-12 col-md-8 col-lg-5 px-5 px-sm-0 mx-auto">
    <h2>User info</h2>
    <%= form_with model:@user, local:true do |f| %>
      <%= render 'layouts/errors', obj: @user %>
      <div class="form-group">
        <%= f.label :name %>
        <%= f.text_field :name, class: "form-control name" %>
      </div>
     <div class="form-group">
        <%= f.label :image %>
        <%= f.file_field :profile_image, class: "form-control-file user_image", accept: 'image/*' %>
      </div>
      <div class="form-group">
        <%= f.label :introduction %>
        <%= f.text_area :introduction, class: "form-control introduction" %>
      </div>
      <div class="form-group">
        <%= f.submit class: 'btn btn-secondary' %>
      </div>
    <% end %>
  </div>
</div>

app/views/users/followers.html.erb
<h2>Follower User</h2>
<table class='table'>
  <thead>
    <tr>
      <th>image</th>
      <th>name</th>
      <th colspan="3"></th>
    </tr>
  </thead>
  <tbody>
    <% @users.each do |user| %>
      <tr>
        <td><%= image_tag user.get_profile_image, size: '50x50' %></td>
        <td><%= user.name %></td>
        <td>フォロー数:<%= user.followings.count %></td>
        <td>フォロワー数:<%= user.followers.count %></td>
        <td><%= link_to 'Show', user_path(user.id) %></td>
      </tr>
    <% end %>
  </tbody>
</table>

app/views/users/followings.html.erb
<h2>Follow User</h2>

<table class='table'>
  <thead>
    <tr>
      <th>image</th>
      <th>name</th>
      <th colspan="3"></th>
    </tr>
  </thead>
  <tbody>
    <% @users.each do |user| %>
      <tr>
        <td><%= image_tag user.get_profile_image, size: '50x50' %></td>
        <td><%= user.name %></td>
        <td>フォロー数:<%= user.followings.count %></td>
        <td>フォロワー数:<%= user.followers.count %></td>
        <td><%= link_to 'Show', user_path(user.id) %></td>
      </tr>
    <% end %>
  </tbody>
</table>

app/views/users/index.html.erb
<div class='container px-5 px-sm-0'>
    <div class="row">
        <div class="col-md-3">
            <h2>User info</h2>
            <%= render 'info', user: current_user %>
            <h2 class="mt-3">New book</h2>
            <%= render 'books/form', book: @book %>
        </div>
        <div class="col-md-8 offset-md-1">
            <h2>Users</h2>
            <%= link_to "グループ作成する", new_group_path %> | <%= link_to "グループ一覧", groups_path %>
            <%= render 'index',users: @users %>
        </div>
    </div>
</div>

app/views/users/show.html.erb
<div class='container px-5 px-sm-0'>
  <div class='row'>
    <div class='col-md-3'>
      <h2>User info</h2>
      <%= render 'info', user: @user %>
      <h2 class="mt-3">New book</h2>
      <%= render 'books/form', book: @book %>
    </div>
    <div class='col-md-8 offset-md-1'>
      <h2>Books</h2>
      <%= render 'books/index',books: @books %>
    </div>
  </div>
</div>